src/pages/background/services/signify.ts

It used the same methodology implemented in Signify/KERIA based on [HTTP Message Signatures](https://httpwg.org/http-extensions/draft-ietf-httpbis-message-signatures.html)
Headers are signed using the selected AID, and includes the fields:
- method
- path
- signify-resource
- signify-timestamp
- origin
`method` and `path` are provided by the webpage and must be treated as unreliable. The other three, 'signify-resource', 'signify-timestamp' and 'origin' are obtained directly from the browser extension. The 'origin' is the web page URL.

Add method to sign headers

---

example-web/my-app/src/App.js
src/components/credentialCard.tsx
src/components/credentialList.tsx
src/components/customRadio.tsx
src/components/identifierCard.tsx
src/components/identifierList.tsx
src/components/main.tsx
src/components/selectCredential.tsx
src/components/selectIdentifier.tsx
src/components/signinCard.tsx
src/components/signinList.tsx
src/pages/background/index.ts
src/pages/content/index.tsx
src/pages/dialog/Dialog.tsx
src/pages/dialog/popupPrompt.tsx
src/pages/dialog/signin.tsx
src/pages/popup/Popup.tsx
src/pages/popup/index.css

Implement credential based signin functionality for webapp.
The web app has two buttons now. One for aid and other for credential.

Feat: add credential based signin for dialog and webapp

---

src/components/identifierCard.tsx
src/components/selectCredential.tsx
src/components/selectIdentifier.tsx
src/pages/background/utils.ts
src/pages/dialog/Dialog.tsx
src/pages/dialog/signin.tsx
src/pages/popup/Popup.tsx

https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/ab31e45b-c31f-47d6-8009-ad146b05992e

Feat: replace custom radio selector by selectable card 

---

example-web/my-app/src/App.js
src/components/signinList.tsx
src/pages/content/index.tsx
src/pages/dialog/Dialog.tsx

@rodolfomiranda I have removed the init-req-* event strings and utilize the TAB_STATE strings. I will further build upon it to fix some issues related to popup state for a tab.

fix: remove init-req* event and replace with TAB_STATE

---

example-web/my-app/package-lock.json
example-web/my-app/package.json
example-web/my-app/src/App.js

@rodolfomiranda I replaced the App.tsx (the code used to communicate with extension) code with a separate package. 
https://www.npmjs.com/package/polaris-web
Please test before merging into the main. 
```
import {
requestAid, // call to select aid for signing in
requestCredential, // call to select credential for signing in
requestAidORCred, // call to select either aid of credential
attemptAutoSignin, // call for auto signin
} from "polaris-web";
```
```
const handleAutoSignin = async () => {
try {
const resp = await attemptAutoSignin();
if (resp?.data) {
alert(
"Signed headers received\n" +
JSON.stringify(resp?.data.headers, null, 2)
);
}
} catch (error) {}
};
```

feat: add polaris-web client library

---

src/_locales/en.json
src/_locales/es-419.json
src/_locales/es.json
src/_locales/index.ts
src/components/identifierList.tsx
src/components/selectIdentifier.tsx
src/components/sidebar.tsx
src/components/ui/dropdown/dropdown.tsx
src/components/ui/dropdown/index.ts
src/components/ui/index.ts
src/config/meta.json
src/pages/dialog/Dialog.tsx
src/pages/dialog/popupPrompt.tsx
src/pages/popup/Popup.tsx
src/screens/config/config.tsx

relevant issue https://github.com/WebOfTrust/signify-browser-extension/issues/82

feat: add dropdown for language selection

---

GETTING_STARTED_VENDOR.md
GETTING_STARTED_WEB_CLI.md

https://github.com/WebOfTrust/signify-browser-extension/issues/72

feat: add ui developer and vendor guides

---

src/pages/background/services/signify.ts
src/pages/content/index.tsx

With that change, if the web send a message of type `TAB_STATE.SELECT_CREDENTIAL` or `TAB_STATE.SELECT_ID_CRED` and add the property `schema` with the schema said, the extension will show only signings with that specific credential.

Filter by schema

---

GETTING_STARTED_WEB_CLI.md
example-web/my-app/src/App.css
example-web/my-app/src/App.js

https://github.com/WebOfTrust/signify-browser-extension/issues/94
https://github.com/WebOfTrust/signify-browser-extension/issues/97

feat: welcome screen for example app

---

example-web/my-app/src/App.css
example-web/my-app/src/App.js
src/_locales/en.json
src/_locales/es-419.json
src/_locales/es.json
src/config/vendor.json
src/pages/background/services/config.ts
src/pages/background/utils.ts
src/pages/dialog/Dialog.tsx
src/pages/dialog/popupPrompt.tsx
src/pages/popup/Popup.tsx
src/screens/config/config.tsx

https://github.com/WebOfTrust/signify-browser-extension/issues/101
https://github.com/WebOfTrust/signify-browser-extension/issues/104

fix: make vendor data optional and use default

---

src/pages/background/utils.ts
src/pages/content/index.tsx
src/pages/popup/Popup.tsx
src/pages/popup/index.tsx

Initial support for Firefox. In order to install in Firefox line 6 in  file `manuscript.json` in `/dist` needs to be modified from
` "service_worker": "service-worker-loader.js"`
to
` "scripts": ["service-worker-loader.js"]`
Pending:
- Auto-signin is not working
- the content script is injected after clicking on the action button
- there are some css changes on the web page after injecting the script

Support for firefox

---

example-web/my-app/src/App.js
example-web/my-app/src/signify-polaris-web/index.js
example-web/my-app/src/signify-polaris-web/pubsub.js
src/components/credentialCard.tsx
src/components/identifierCard.tsx
src/components/sidebar.tsx
src/components/signinCard.tsx
src/pages/background/index.ts
src/pages/content/index.tsx
src/pages/dialog/Dialog.tsx
src/screens/config/config.tsx
src/screens/signin/index.tsx

Hey @rodolfomiranda 
Please review the changes I made for firefox compatibility. 
There are some temporary changes related to the signify-polaris-web package.

DO NOT MERGE: Feat/temp firefox

---

package.json
vite.config.ts

https://github.com/WebOfTrust/signify-browser-extension/issues/118
run `npm run build` to create a build for chrome, destination folder: `dist/chrome`
run `npm run build:firefox` to create a build for firefox, destination folder: `dist/firefox`

feat: add build step for firefox

---

src/components/ui/switch/switch.tsx
src/pages/background/index.ts
src/pages/background/services/signify.ts
src/screens/signin/index.tsx

Resolves this issues
https://github.com/WebOfTrust/signify-browser-extension/issues/123
https://github.com/WebOfTrust/signify-browser-extension/issues/124

feat: add a loop while fetching identifiers

---

src/config/types.ts
src/pages/background/handlers/resource.ts
src/pages/background/resource/headers/index.ts
src/pages/background/resource/signin/index.ts
src/pages/background/services/signify.ts

@rodolfomiranda pointed out a critical bug where before providing signatures we were not checking if autoSignin was true for the provided aid/credential or not. This PR fixes that.
Relevant Comment: https://github.com/WebOfTrust/signify-browser-extension/pull/171#discussion_r1588332747

fix: check signin autoSignin flag before signature headers

---

src/components/ui/input/input.tsx
src/pages/background/services/config.ts
src/pages/background/services/session.ts

Trailing slash in agent url was appending double slashs and failing the api call
**Nord Vlei extension**
**Signify Extension**
[Relevant Reg Pilot Issue](https://github.com/GLEIF-IT/reg-pilot-webapp/issues/86)

fix: remove trailing slash from agent and boot url

---

src/pages/background/index.ts

Service worker in manifest version 3 gets inactive if there is no activity for some time.
This causes a glitch in signify at certain points in workflow
[Signify Client not connected](https://www.loom.com/share/7e4872f6b6cf4db3951309a9ac02f36e?sid=3ae1e26b-2a78-4493-a053-cdb0b28c5c16)
To cure this, an interval is added that keeps service worker activated during the session. 
[SW activated](https://www.loom.com/share/a7c328026b2946798d5aa6c432aad4d9)
This ensures that communication with content script and service worker does not get blocked due to a pause.

fix: keep sw activated during session

---

src/pages/background/services/signify.ts

Not sure how to run tests but this shouldn't break anything I think.

Fixed spelling of extension in log message

---

src/screens/config/config.tsx
src/screens/signin/index.tsx

Related Link: https://github.com/WebOfTrust/signify-browser-extension/issues/216
@daidoji 
Here is a fix for #216 
Now agentUrl, or bootUrl changes are reflected upon click on Save.
I have attached a video for illustration.
https://github.com/user-attachments/assets/6f548ce8-d622-43eb-8a94-4cdb140840a6

fix: onboarding agenturl fix with save button

---

src/components/selectCredential.tsx
src/pages/background/index.ts
src/pages/background/services/browser-storage.ts
src/pages/background/services/user.ts

**Linked Issue:** https://github.com/WebOfTrust/signify-browser-extension/issues/218
**Problem:**
passcode is stored in the browser extension's local storage, which raises security issues and can be sneak peaked using multiple plugins.
passcode and other user related info e.g controlled ID are moved to session storage. 
**Behaviour Change**
Earlier, if extension was unlocked it remained unlocked until timeout occurred. It means even if browser is closed and reopened before the timeout, extension remained unlocked.
Now extension moves to a locked state whenever the user closes the browser or timeout reaches.

feat: move passcode to session storage from local
